### ISSUE TITLE
tvheadend ubuntu dont get streamlink latest

### ISSUE THREAD

**Issue by Toei79** [cgomesu/tvhlink#14]
hi 

idk where place this, maybe here? my issue its this, i have tvheadend, on ubuntu, but streamlink can only get until 2.3 if you do sudo apt
then my option its install through pip 

tvheadend get perfectly fine when its thought sudo apt install but because i cant get latest i need use pip method installation under this streamlink get installed in
/.local/bin/streamlink

when i try run on command line it works but when i try with pipe on tvheadend it don't work 

example

pipe:///usr/bin/env ~/.local/bin/ streamlink --stdout --default-stream 720p --url https://www.earthcam.com/usa/louisiana/neworleans/bourbonstreet/?cam=catsmeow2

pipe:///usr/bin/env /.local/bin/streamlink --stdout --default-stream 720p --url https://www.earthcam.com/usa/louisiana/neworleans/bourbonstreet/?cam=catsmeow2

none of those work.

**Comment by cgomesu** [comment]
hi, @Toei79 . 

> my issue its this, i have tvheadend, on ubuntu, but streamlink can only get until 2.3 if you do sudo apt
> then my option its install through pip

installing streamlink via pip is actually the recommended way.  that is the same method I use to install inside my docker containers, for example. (see [tvhlink/tools/docker/streamlink_for_tvh_container.sh](https://github.com/cgomesu/tvhlink/blob/master/tools/docker/streamlink_for_tvh_container.sh).)
 
> tvheadend get perfectly fine when its thought sudo apt install but because i cant get latest i need use pip method installation under this streamlink get installed in
> /.local/bin/streamlink

if you use `pip` without `sudo` permission (or the root user itself), then the package is installed under the `.local` dir of **the user** (i.e., `/home/${USER}/.local/`), which is not available to TVHeadend.

> when i try run on command line it works but when i try with pipe on tvheadend it don't work

yeah, because your user can find `/home/${USER}/.local/bin/streamlink` but TVH won't find it, owing to permissions and $PATH.

to fix this, first uninstall stramlink for your user via `pip`.  log into the machine using your user and then run the following:

```
pip uninstall streamlink
```

if you did not uninstall the `apt` version of streamlink, then now remove it as well:

```
sudo apt purge streamlink
```

now your own user and `root` should not be able to find `streamlink` at all.  that is, the following commands

```
which streamlink
```
```
sudo which streamlink
```

should both return nothing.

then install `streamlink` globally via `pip`:

```
sudo pip install streamlink
```

and then check that `which streamlink` finds it outside your own user's home directory and check its version to make sure it is the latest (`3.2.0`):

```
streamlink --version
```

if everything looks good, go check to TVH, *use the original `pipe` commands shown on the tutorial*, and check that it works.  here's an example of pipe command for the Al Jazeera (EN) Youtube live feed that TVH should try to run:

```
pipe:///usr/bin/env streamlink --stdout --hls-live-edge 6 --ringbuffer-size 32M -4 --default-stream 720p,best --url https://youtube.com/user/AlJazeeraEnglish
```

**Comment by Toei79** [comment]
man amazing, i was all day try to figure out, i even install pip but yea you explain what happens, so like sudo make the magic all back to normal
i just like 4 months on linux,  i tried before but never figure out all this time i keep with the same version 2.3 , but now i have the latests thanks

this time streamlink it be there with this installation

/usr/local/bin/streamlink


i read this yesterday so i never give the try just today hope be ok

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.1.3; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.

my ubuntu not longer accept updates.

**Comment by Toei79** [comment]
hi question you able to play this one?

https://www.earthcam.com/usa/newyork/statueofliberty/?cam=liberty_str

for some reason i cant

**Comment by cgomesu** [comment]
glad you managed to fix the issue and welcome to the GNU/Linux world :rocket: 

> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

this is safe to ignore

> WARNING: You are using pip version 21.1.3; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.

run `pip install --upgrade pip` to upgrade Python's package manager (pip) and this warning should go away

> hi question you able to play this one?
>
> https://www.earthcam.com/usa/newyork/statueofliberty/?cam=liberty_str

I cannot.  see https://streamlink.github.io/plugins.html#earthcam for information about restrictions though.  for any other Streamlink related question, please direct them to the maintainers on the GIthub repo: https://github.com/streamlink/streamlink

I'll go ahead and close this issue because it looks like the original one has been fixed. if you have other issues with the TVHlink integration, please open a new one.
