### ISSUE TITLE
Streamlink on Libreelec

### ISSUE THREAD

**Issue by ccontrolled** [cgomesu/tvhlink#20]
Is it possible to install streamlink on Libreelec-Matrix? How?

**Comment by cgomesu** [comment]
you sure can.  take a look at https://wiki.libreelec.tv/installation/docker to learn how to run Docker containers with your LibreElec host.  then pull and run the Tvheadend container and use [my docker helper script](https://raw.githubusercontent.com/cgomesu/tvhlink/master/tools/docker/streamlink_for_tvh_container.sh) to install and update streamlink within the Tvheadend container.

**Comment by ccontrolled** [comment]
Thank you so far! Unfortunately I am no specialist. I created the tvheadend docker, started it, 
logged in with "docker exec -it tvheadend /bin/bash" , created your script with vi, executed it 
with good result *Reached EOF without critical errors.* so that I can execute streamlink inside 
the docker now. 
But how do I call streamlink from outside the docker (from the libreelec bash)? 
A tvheadend-MUX with:
pipe://docker exec tvheadend /usr/bin/streamlink --stdout --default-stream 720p,best --url https://www.youtube.com/watch?v=ntmPIzlkcJk
does not work! :(

**Comment by cgomesu** [comment]
> I created the tvheadend docker, started it, logged in with "docker exec -it tvheadend /bin/bash" , created your script with vi, executed it with good result Reached EOF without critical errors. so that I can execute streamlink inside the docker now.

this should work for a single run but whenever you change your container or there's a streamlink update, you'll need to manually run the script again for the changes to take effect.  fortunately, there's a much easier solution.  linuxserver.io containers allow you to store custom scripts at the container's `/custom-cont-init.d` dir and any script placed there will be executed whenever the container is initialized (see https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers). to implement this, do the following:

1. ssh into your libreelec 
2. create a directory called `custom-cont-init.d` in `/storage/`: `mkdir -p /storage/custom-cont-init.d`
3. download the script to the new dir: `curl -o /storage/custom-cont-init.d/streamlink_for_tvh_container.sh https://raw.githubusercontent.com/cgomesu/tvhlink/master/tools/docker/streamlink_for_tvh_container.sh`
4. make the script executable: `chmod +x /storage/custom-cont-init.d/streamlink_for_tvh_container.sh`
5. configure your Tvheadend Docker container to map your host's `/storage/custom-cont-init.d` onto the container's `/custom-cont-init.d` with the argument `-v /storage/custom-cont-init.d:/custom-cont-init.d`
6. start/restart your container and pay close attention to the logs (`docker logs --follow tvheadend`). you should see the script executing as soon as the container starts.
7. if everything is looking good, then go to your Tvheadend server and configure it just as described in the tutorial.

this procedure is also outlined in the tutorial: https://cgomesu.com/blog/Tvhlink/#docker-installation-1.

> But how do I call streamlink from outside the docker (from the libreelec bash)?

why would you want to do that? it is your Tvheadend server that needs to use streamlink and if you followed the procedure above, it should be able to do so in order to pipe the streams to any of its clients. if you also want to use your libreelec as client, then follow this: https://cgomesu.com/blog/Tvhlink/#tvh-kodi-pvr-addon.

**Comment by ccontrolled** [comment]
This morning I did create and start streamlink_for_tvh_container.sh inside(!) the docker (after that I at least had internet with 
ping google.com inside the docker; however the MUX-Commandline yet not worked;no signal) before your last  comment.
How does the complete command line look for the configuration of the docker? The -v is "version" so I guess it would not be
docker config tvheadend -v /storage/custom-cont-init.d:/custom-cont-init.d   ----> unknown shorthand flag: 'v' in -v

(Libreelec with TVHEADEND and pvr.hts did already run here since years for watching TV on my RPi before the creation of 
the additional tvheadend-docker; is there a second parallel running tvheadend-server in the docker?)

**Comment by cgomesu** [comment]
> however the MUX-Commandline yet not worked;no signal

I don't know what you mean by that.  If you want to test streamlink within the container, then run something like `streamlink https://www.youtube.com/c/FRANCE24` (press `Ctrl+c` to interrupt) inside the container.

> How does the complete command line look for the configuration of the docker?

The configuration I mentioned is the one for the container, not for Docker itself.   You need to instruct the container to map a host directory to a container directory.  There are multiple ways of doing this.  See volumes (https://docs.docker.com/storage/volumes/).  

I strongly suggest you to use Portainer no manage Docker containers (https://www.portainer.io/).  It's going to make your life a lot easier.

> (Libreelec with TVHEADEND and pvr.hts did already run here since years for watching TV on my RPi before the creation of
the additional tvheadend-docker; is there a second parallel running tvheadend-server in the docker?)

Yes, this make things more complicated than they should be.  I think you are using the addon that installs a Tvheadend server on your LibreElec host.  If this is the case, then you "just" need to install streamlink on your host as well.  The issue here is that LibreElec will make it hard for you to do so because it was made to work with addons instead and won't have access to other package managers like `apt` or `pip` to install external packages.  Running Tvheadend within a Docker container will give you more flexibility.  In any case, there is no reason here to run multiple Tvheadend servers with the same host.  Choose one before moving forward.

**Comment by ccontrolled** [comment]
Thank you so far, but as it is not possible to install streamlink on the Libreelec host as well (may be one day in fiuture there 
will be an addon for libreelec as there is a good working addon for ffmpeg) I would not like to buy portainer (still do not know how to manage the tvheadend-container with the -v /storage/custom-cont-init.d:/custom-cont-init.d  -command)  
and transport all my channels into the docker (how?) where I have to start an new tvheadend-service after 
uninstalling/deactivating tvheadend on the host.
Former I used OSMC where I did build streamlink but as the pvr.hts did no more work on it I changed to libreelec.

So I will wait for a streamlink-addon one day (Btw I am sure YOU could build one ;)

**Comment by cgomesu** [comment]
>  I would not like to buy portainer

just like Docker, there is a community edition for Portainer that is free for home users like you and me: https://docs.portainer.io/start/install/server/docker/linux.

> (still do not know how to manage the tvheadend-container with the -v /storage/custom-cont-init.d:/custom-cont-init.d -command)

once you get portainer up and running, go to add container > advanced container settings > volumes > map additional volume.

> transport all my channels into the docker (how?) where I have to start an new tvheadend-service after
uninstalling/deactivating tvheadend on the host

https://duckduckgo.com/?q=tvheadend+backup+configuration

> So I will wait for a streamlink-addon one day

there's obviously a learning curve to Docker and I think you are still learning the very basics of it.  I should say, however, that the time spent learning how to use it is worthwhile.  Docker and Portainer are two very well documented projects (https://docs.docker.com/, https://docs.portainer.io/) and if I were in your position, I'd definitely invest the time to play around with them.  you'll find you can do a lot more with your LibreElec than just play videos.

**Comment by ccontrolled** [comment]
Ok so far; if I really wold start tvheadend in the docker one day, do you have some simple command lines to set up
an sftp server inside the docker to get my channels into the tvheadend-docker?

**Comment by cgomesu** [comment]
use `scp` (https://www.ssh.com/academy/ssh/scp)
