### ISSUE TITLE
earthcam

### ISSUE THREAD

**Issue by Toei79** [cgomesu/tvhlink#4]
sorry its not issue better ask for help i try run some links from earthcam on tvheadend without success

https://www.earthcam.com/usa/florida/keywest/?cam=irishkevins

its in earthcam server.

its reads by tvheadend log for what i see but dont play , i try with vlc.

also how i can install a plugin ? i need one for ssh01

https://ssh101.com/detail.php?id=shovvplus

example of one channel, by documentation shows its available but idk how install it, 

i run streamlink https://ssh101.com/detail.php?id=shovvplus
and give error not plugin.

**Comment by cgomesu** [comment]
> sorry its not issue better ask for help i try run some links from earthcam on tvheadend without success
> 
> https://www.earthcam.com/usa/florida/keywest/?cam=irishkevins
> 
> its in earthcam server.
> 
> its reads by tvheadend log for what i see but dont play , i try with vlc.

I can find two different streams at the provided URL: `450p (worst)`, `live (best)`. `live` uses [RTMP](https://en.wikipedia.org/wiki/Real-time_Messaging_Protocol), while `450p` uses [HLS](https://en.wikipedia.org/wiki/HTTP_Live_Streaming).  Have you tested both?  Try using the latter (`450p`) in your `pipe://` command instead of the former.

> also how i can install a plugin ? i need one for ssh01

You can request a new plugin at the official [Streamlink Github repo](https://github.com/streamlink/streamlink).  First, however, go over their open and closed issues to make sure no one has requested such a plugin before.  Then, read what their [CONTRIBUTING.md](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests) guide has to say about plugin requests and if everything looks good, open a new issue as *plugin request*.

**Comment by Toei79** [comment]
sorry im too new how is syntax? for place it in tvheadend i know pipe i did your tutorial for youtube from the blog

i found this 
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/ssh101.py

looks like plugin idk way to install it,

i cant locate folder on my pi ubuntu

**Comment by cgomesu** [comment]
> sorry im too new how is syntax? for place it in tvheadend i know pipe i did your tutorial for youtube from the blog

in your tvheadend server, use `pipe:///usr/bin/env streamlink --stdout --default-stream 450p --url https://www.earthcam.com/usa/florida/keywest/?cam=irishkevins` when configuring the mux for this particular stream.

> https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/ssh101.py

it seems that ssh101 is already supported.  you do not need to enable anything.  plugins are automatically selected based on the stream `url`. however, the URL you mentioned before (https://ssh101.com/detail.php?id=shovvplus) does not match the current URL regex for that plugin (https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/ssh101.py#L12). apparently, you have to use the address in the embed code (`https://ssh101.com/securelive/index.php?id=shovvplus`) but I'm not able to find any playable stream there via `streamlink` anyway. the plugin might be outdated. please [open an issue at the Streamlink repo](https://github.com/streamlink/streamlink/issues) to let the maintainers know about it.

**Comment by Toei79** [comment]
thanks carlos, question those youtube on tvheadend dont expire after some hours?

you able to play earthcam link with 450p?
i try tonight

i will open sone ssh101 have lot channels

**Comment by cgomesu** [comment]
> question those youtube on tvheadend dont expire after some hours?

I'm not sure I understand you question...  a stream will terminate if the user/channel owner restarts it but as long as it continues being streamed by the same Youtube channel, Streamlink should always be able to find it if you provide the channel URL as source (e.g., https://www.youtube.com/user/france24english/live) and the channel is broadcasting only one live stream.

> you able to play earthcam link with 450p?

yes

> i try tonight

please do follow up. if it works, go ahead and close this issue; otherwise, post your tvheadend log.

**Comment by Toei79** [comment]
thanks i try tonight and update

no what i mean its youtube link expire after 6 or 4 hours (when you place  just yhe link directly in tivimate x example)
i dont know if streamlink make keep going further

i use tvheadend n3u on tivimate

**Comment by cgomesu** [comment]
> no what i mean its youtube link expire after 6 or 4 hours (when you place just yhe link directly in tivimate x example)
i dont know if streamlink make keep going further

I've had streams going for days. depending on what you are trying to do, tvheadend will automatically retry the connection until it gets data.

**Comment by Toei79** [comment]
thanks now runs fine earthcam ones

im trying this one its a hls stream

pipe:///usr/bin/env streamlink --stdout --default-stream best --url https://hd-auth.skylinewebcams.com/live.m3u8?a=ot89jedjhs1p7alnpooc7nkme2

this its structure? i found running streamlink url,  live (worst , best)

my streamlink version its 2.2 thats fine?  i mean late one its 2.3 i install it thorugh apt

**Comment by cgomesu** [comment]
> thanks now runs fine earthcam ones

glad to learn that the issue was fixed, @Toei79 .

> im trying this one its a hls stream
>
> pipe:///usr/bin/env streamlink --stdout --default-stream best --url https://hd-auth.skylinewebcams.com/live.m3u8?a=ot89jedjhs1p7alnpooc7nkme2

you can find a list of all currently supported plugins at https://streamlink.github.io/plugin_matrix.html . please direct any further questions related to the Streamlink application (plugins and usage) to the actual maintainers on their official Github repo.

closing this issue because it has been solved.
